lib/budgco_web/router.ex
defmodule BudgcoWeb.Router do
  use BudgcoWeb, :router

  import BudgcoWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_root_layout, {BudgcoWeb.LayoutView, :root}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BudgcoWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BudgcoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/telemetry_dashboard", metrics: BudgcoWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/auth", BudgcoWeb do
    get "/:provider", UserSessionController, :request
    get "/:provider/callback", UserSessionController, :callback
  end

  scope "/", BudgcoWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", BudgcoWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
    live "/fantasy", FantasyLive
    live "/rankings", PersonalRankingsLive
    live "/dashboard", DashboardLive
    live "/dashboard/customer", DashboardCustomerLive
    live "/dashboard/account", DashboardAccountLive
    live "/home", HomeLive
  end

  scope "/", BudgcoWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/budgco_web/views/layout_view.ex
defmodule BudgcoWeb.LayoutView do
  use BudgcoWeb, :view
end

lib/budgco_web/templates/layout/_user_menu.html.eex
<ul>
<%= if @current_user do %>
  <li><%= @current_user.email %></li>
  <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/budgco_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Budgco</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <main role="main" class="container flex w-full">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/budgco_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Budgco</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
      <section class="flex flex-row justify-center w-full">
        <nav class="flex flex-row" role="navigation">
          <div class="flex flex-col items-center justify-center w-20 h-20 text-5xl">💰</div>
          <ul>
              <li><%= link "Dashboard", to: Routes.live_path(BudgcoWeb.Endpoint, BudgcoWeb.DashboardLive) %></li>
              <li><%= link "Fantasy", to: Routes.live_path(BudgcoWeb.Endpoint, BudgcoWeb.FantasyLive) %></li>
              <li><%= link "My Rankings", to: Routes.live_path(BudgcoWeb.Endpoint, BudgcoWeb.PersonalRankingsLive) %></li>
              <li><%= link "Home", to: Routes.live_path(BudgcoWeb.Endpoint, BudgcoWeb.HomeLive) %></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
          <%= render "_user_menu.html", assigns %>
        </nav>
      </section>
    </header>
    <main role="main" class="flex flex-row justify-center w-full">
      <%= @inner_content %>
    </main>
  </body>
</html>